import "leaflet/dist/leaflet.css";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Footerr from "@/components/Footerr";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <body
  // style={{ backgroundColor: "white", color:"black" }}
  className={`${geistSans.variable} ${geistMono.variable} h-[1000px] overflow-x-hidden antialiased`}
>

        <Header/>
        {children}
        <Footer/>
        <Footerr/>
      </body>
    </html>
  );
}
